// flow-typed signature: 0ccdd2330ad1345d0835a103a829ff58
// flow-typed version: <<STUB>>/babel-preset-es2015_v^6.18.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-es2015/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-es2015/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015/lib/index'>;
}
