// flow-typed signature: c494fb37eb717f55794b2dafc70ac68d
// flow-typed version: <<STUB>>/eslint-config-standard-jsx_v^3.2.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-standard-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-standard-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-standard-jsx/test/basic' {
  declare module.exports: any;
}

declare module 'eslint-config-standard-jsx/test/validate-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-standard-jsx/index' {
  declare module.exports: $Exports<'eslint-config-standard-jsx'>;
}
declare module 'eslint-config-standard-jsx/index.js' {
  declare module.exports: $Exports<'eslint-config-standard-jsx'>;
}
declare module 'eslint-config-standard-jsx/test/basic.js' {
  declare module.exports: $Exports<'eslint-config-standard-jsx/test/basic'>;
}
declare module 'eslint-config-standard-jsx/test/validate-config.js' {
  declare module.exports: $Exports<'eslint-config-standard-jsx/test/validate-config'>;
}
