// flow-typed signature: 594c3df106615f0cac8ce316532209d3
// flow-typed version: <<STUB>>/react-native-web_v^0.0.49/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-web/dist/apis/Animated/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppRegistry/ReactNativeApp' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppRegistry/renderApplication' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppState/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AsyncStorage/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Dimensions/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/I18nManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/InteractionManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/NetInfo/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/PanResponder/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/PixelRatio/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Platform/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/createReactStyleObject' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/css' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/expandStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/i18nStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/normalizeValue' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/processTextShadow' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/processTransform' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/processVendorPrefixes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/StyleSheetValidation' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/UIManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Vibration/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ActivityIndicator/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Image/ImageResizeMode' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Image/ImageStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Image/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ListView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ListView/ListViewDataSource' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ListView/ListViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ProgressBar/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ScrollView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ScrollView/ScrollViewBase' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/StaticContainer/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/StaticRenderer/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Switch/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Text/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Text/TextStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/TextInput/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/TextInput/TextInputState' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/BoundingDimensions' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/ensureComponentIsNative' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/ensurePositiveDelayProps' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/Position' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/Touchable' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableBounce' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableHighlight' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableOpacity' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableWithoutFeedback' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/View/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/View/ViewStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/core' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/applyLayout/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/applyNativeMethods/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/createDOMElement/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/dismissKeyboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/findNodeHandle/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/flattenStyle/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/injectResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/merge/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/multiplyStyleLengthValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/NativeMethodsMixin/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/NativeModules/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/normalizeColor/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/normalizeNativeEvent' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/polyfills/Set' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/ReactNativePropRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/ScrollResponder/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/BaseComponentPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/BorderPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/ColorPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/createStrictShapeTypeChecker' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/EdgeInsetsPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/LayoutPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/PointPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/StyleSheetPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/TextPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/TransformPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/ReactNative' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/tests.webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-web/dist/apis/Animated/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Animated/index'>;
}
declare module 'react-native-web/dist/apis/AppRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppRegistry/index'>;
}
declare module 'react-native-web/dist/apis/AppRegistry/ReactNativeApp.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppRegistry/ReactNativeApp'>;
}
declare module 'react-native-web/dist/apis/AppRegistry/renderApplication.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppRegistry/renderApplication'>;
}
declare module 'react-native-web/dist/apis/AppState/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppState/index'>;
}
declare module 'react-native-web/dist/apis/AsyncStorage/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AsyncStorage/index'>;
}
declare module 'react-native-web/dist/apis/Dimensions/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Dimensions/index'>;
}
declare module 'react-native-web/dist/apis/I18nManager/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/I18nManager/index'>;
}
declare module 'react-native-web/dist/apis/InteractionManager/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/InteractionManager/index'>;
}
declare module 'react-native-web/dist/apis/NetInfo/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/NetInfo/index'>;
}
declare module 'react-native-web/dist/apis/PanResponder/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/PanResponder/index'>;
}
declare module 'react-native-web/dist/apis/PixelRatio/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/PixelRatio/index'>;
}
declare module 'react-native-web/dist/apis/Platform/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Platform/index'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/createReactStyleObject.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/createReactStyleObject'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/css.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/css'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/expandStyle.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/expandStyle'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/i18nStyle.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/i18nStyle'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/index'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/normalizeValue.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/normalizeValue'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/processTextShadow.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/processTextShadow'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/processTransform.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/processTransform'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/processVendorPrefixes.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/processVendorPrefixes'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/StyleSheetValidation.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/StyleSheetValidation'>;
}
declare module 'react-native-web/dist/apis/UIManager/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/UIManager/index'>;
}
declare module 'react-native-web/dist/apis/Vibration/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Vibration/index'>;
}
declare module 'react-native-web/dist/components/ActivityIndicator/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ActivityIndicator/index'>;
}
declare module 'react-native-web/dist/components/Image/ImageResizeMode.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Image/ImageResizeMode'>;
}
declare module 'react-native-web/dist/components/Image/ImageStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Image/ImageStylePropTypes'>;
}
declare module 'react-native-web/dist/components/Image/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Image/index'>;
}
declare module 'react-native-web/dist/components/ListView/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ListView/index'>;
}
declare module 'react-native-web/dist/components/ListView/ListViewDataSource.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ListView/ListViewDataSource'>;
}
declare module 'react-native-web/dist/components/ListView/ListViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ListView/ListViewPropTypes'>;
}
declare module 'react-native-web/dist/components/ProgressBar/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ProgressBar/index'>;
}
declare module 'react-native-web/dist/components/ScrollView/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ScrollView/index'>;
}
declare module 'react-native-web/dist/components/ScrollView/ScrollViewBase.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ScrollView/ScrollViewBase'>;
}
declare module 'react-native-web/dist/components/StaticContainer/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/StaticContainer/index'>;
}
declare module 'react-native-web/dist/components/StaticRenderer/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/StaticRenderer/index'>;
}
declare module 'react-native-web/dist/components/Switch/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Switch/index'>;
}
declare module 'react-native-web/dist/components/Text/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Text/index'>;
}
declare module 'react-native-web/dist/components/Text/TextStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Text/TextStylePropTypes'>;
}
declare module 'react-native-web/dist/components/TextInput/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/TextInput/index'>;
}
declare module 'react-native-web/dist/components/TextInput/TextInputState.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/TextInput/TextInputState'>;
}
declare module 'react-native-web/dist/components/Touchable/BoundingDimensions.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/BoundingDimensions'>;
}
declare module 'react-native-web/dist/components/Touchable/ensureComponentIsNative.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/ensureComponentIsNative'>;
}
declare module 'react-native-web/dist/components/Touchable/ensurePositiveDelayProps.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/ensurePositiveDelayProps'>;
}
declare module 'react-native-web/dist/components/Touchable/Position.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/Position'>;
}
declare module 'react-native-web/dist/components/Touchable/Touchable.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/Touchable'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableBounce.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableBounce'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableHighlight.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableHighlight'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableOpacity.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableOpacity'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableWithoutFeedback.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableWithoutFeedback'>;
}
declare module 'react-native-web/dist/components/View/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/View/index'>;
}
declare module 'react-native-web/dist/components/View/ViewStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/View/ViewStylePropTypes'>;
}
declare module 'react-native-web/dist/core.js' {
  declare module.exports: $Exports<'react-native-web/dist/core'>;
}
declare module 'react-native-web/dist/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/index'>;
}
declare module 'react-native-web/dist/modules/applyLayout/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/applyLayout/index'>;
}
declare module 'react-native-web/dist/modules/applyNativeMethods/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/applyNativeMethods/index'>;
}
declare module 'react-native-web/dist/modules/createDOMElement/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/createDOMElement/index'>;
}
declare module 'react-native-web/dist/modules/dismissKeyboard/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/dismissKeyboard/index'>;
}
declare module 'react-native-web/dist/modules/findNodeHandle/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/findNodeHandle/index'>;
}
declare module 'react-native-web/dist/modules/flattenStyle/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/flattenStyle/index'>;
}
declare module 'react-native-web/dist/modules/injectResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/injectResponderEventPlugin'>;
}
declare module 'react-native-web/dist/modules/merge/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/merge/index'>;
}
declare module 'react-native-web/dist/modules/multiplyStyleLengthValue/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/multiplyStyleLengthValue/index'>;
}
declare module 'react-native-web/dist/modules/NativeMethodsMixin/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/NativeMethodsMixin/index'>;
}
declare module 'react-native-web/dist/modules/NativeModules/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/NativeModules/index'>;
}
declare module 'react-native-web/dist/modules/normalizeColor/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/normalizeColor/index'>;
}
declare module 'react-native-web/dist/modules/normalizeNativeEvent.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/normalizeNativeEvent'>;
}
declare module 'react-native-web/dist/modules/polyfills/Set.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/polyfills/Set'>;
}
declare module 'react-native-web/dist/modules/ReactNativePropRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/ReactNativePropRegistry/index'>;
}
declare module 'react-native-web/dist/modules/ScrollResponder/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/ScrollResponder/index'>;
}
declare module 'react-native-web/dist/propTypes/BaseComponentPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/BaseComponentPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/BorderPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/BorderPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/ColorPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/ColorPropType'>;
}
declare module 'react-native-web/dist/propTypes/createStrictShapeTypeChecker.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/createStrictShapeTypeChecker'>;
}
declare module 'react-native-web/dist/propTypes/EdgeInsetsPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/EdgeInsetsPropType'>;
}
declare module 'react-native-web/dist/propTypes/LayoutPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/LayoutPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/PointPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/PointPropType'>;
}
declare module 'react-native-web/dist/propTypes/StyleSheetPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/StyleSheetPropType'>;
}
declare module 'react-native-web/dist/propTypes/TextPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/TextPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/TransformPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/TransformPropTypes'>;
}
declare module 'react-native-web/dist/ReactNative.js' {
  declare module.exports: $Exports<'react-native-web/dist/ReactNative'>;
}
declare module 'react-native-web/dist/tests.webpack.js' {
  declare module.exports: $Exports<'react-native-web/dist/tests.webpack'>;
}
