// @flow

// Export the full public API of react-native-web
export {
  // top-level API
  createElement,
  findNodeHandle,
  render,
  unmountComponentAtNode,
  // modules
  processColor,
  NativeModules,
  TextPropTypes,
  ViewPropTypes,
  // APIs
  AccessibilityInfo,
  Animated,
  AppRegistry,
  AppState,
  AsyncStorage,
  BackHandler,
  DeviceInfo,
  Dimensions,
  Easing,
  I18nManager,
  InteractionManager,
  Keyboard,
  LayoutAnimation,
  NativeEventEmitter,
  NetInfo,
  PanResponder,
  PixelRatio,
  Platform,
  Share,
  StyleSheet,
  UIManager,
  Vibration,
  // components
  ActivityIndicator,
  ART,
  Button,
  CheckBox,
  FlatList,
  Image,
  ImageBackground,
  KeyboardAvoidingView,
  ListView,
  Modal,
  Picker,
  ProgressBar,
  RefreshControl,
  SafeAreaView,
  ScrollView,
  SectionList,
  Slider,
  StatusBar,
  SwipeableFlatList,
  SwipeableListView,
  Switch,
  Text,
  TextInput,
  Touchable,
  TouchableHighlight,
  TouchableNativeFeedback,
  TouchableOpacity,
  TouchableWithoutFeedback,
  View,
  VirtualizedList,
  YellowBox,
  // propTypes
  ColorPropType,
  EdgeInsetsPropType,
  PointPropType,
  // compat (components)
  DatePickerIOS,
  DrawerLayoutAndroid,
  ImageEditor,
  ImageStore,
  InputAccessoryView,
  MaskedViewIOS,
  NavigatorIOS,
  PickerIOS,
  ProgressBarAndroid,
  ProgressViewIOS,
  SegmentedControlIOS,
  SnapshotViewIOS,
  TabBarIOS,
  ToastAndroid,
  ToolbarAndroid,
  ViewPagerAndroid,
  // compat (apis)
  ActionSheetIOS,
  AlertIOS,
  CameraRoll,
  DatePickerAndroid,
  ImagePickerIOS,
  PermissionsAndroid,
  PushNotificationIOS,
  Settings,
  StatusBarIOS,
  Systrace,
  TimePickerAndroid,
  TVEventHandler,
  VibrationIOS,
} from 'react-native-web'

// APIs
export * as Alert from './apis/Alert'
export * as Clipboard from './apis/Clipboard'
export * as Linking from './apis/Linking'

// components
export { default as WebView } from './components/WebView'
